# Changing this file necessitates a server restart
name: "JuliaCon Proceedings"
abbreviation: "JuliaCon"
tagline: "JuliaCon -- an open community conference."
logo_url: "https://juliacon.org/2019/assets/img/logo.svg"
url: "https://proceedings.juliacon.org"
editor_email: "vchuravy@gmail.org"
noreply_email: "juliacon@julialang.org"
twitter: "JuliaConOrg"
twitter_issn: "2642-4029"
google_analytics: ""
github: "arfon/juliacon-proceedings"
reviews: "JuliaCon/proceedings-review"
papers_html_url: "https://www.theoj.org/pjc-papers"
product: "papers" # the *thing* being submitted for review
reviewers: "https://bit.ly/joss-reviewers"
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the PJC submission criteria.
paper_types: ["full paper", "extended abstract"]
