# Changing this file necessitates a server restart
name: "JuliaCon Proceedings"
abbreviation: "PJC"
tagline: "proceedings for JuliaCon -- an open community conference."
logo_url: "https://juliacon.org/2019/assets/img/logo.svg"
url: "http://pjc.theoj.org"
editor_email: "vchuravy@mit.edu"
noreply_email: "noreply@pjc.theoj.org"
twitter: "JuliaConOrg"
twitter_issn: ""
google_analytics: ""
github: "arfon/juliacon-proceedings"
reviews: "JuliaCon/proceedings-review"
papers_html_url: "https://www.theoj.org/pjc-papers"
product: "papers" # the *thing* being submitted for review
reviewers: "https://bit.ly/joss-reviewers"
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the PJC submission criteria.
paper_types: []
